#ifndef RENDERPATH_H
#define RENDERPATH_H

#define RENDER_PATH_POTATO     0U
#define RENDER_PATH_CLASSIC_1X 1U
#define RENDER_PATH_CLASSIC_2X 2U
#define RENDER_PATH_STAGED     3U

#define RENDER_PATH_IS_CLASSIC(m) (((m) == RENDER_PATH_CLASSIC_1X) || ((m) == RENDER_PATH_CLASSIC_2X))
#define RENDER_PATH_IS_STAGED(m)  ((m) == RENDER_PATH_STAGED)

#endif
